### ISSUE TITLE
does not build with ocaml 5.0

### ISSUE THREAD

**Issue by solsticedhiver** [libguestfs/virt-v2v#27]
from what I understand the build fails because of ocaml 5.0.
using ocaml-libvirt-git, the build (either 2.2.0 or 2.3.4 or git) fails with:

```
make[2] : on entre dans le répertoire « /home/solstice/asp/AUR/virt-v2v/src/virt-v2v-2.3.4/common/mlstdutils »
  CC       libmlstdutils_a-dummy.o
  OCAMLCMI guestfs_config.cmi
  OCAMLCMI stringMap.cmi
  OCAMLCMI stringSet.cmi
  OCAMLCMI std_utils.cmi
  OCAMLOPT guestfs_config.cmx
  OCAMLC   guestfs_config.cmo
  OCAMLC   stringSet.cmo
  OCAMLOPT stringMap.cmx
  OCAMLOPT stringSet.cmx
  OCAMLC   stringMap.cmo
  OCAMLC   std_utils.cmo
  OCAMLOPT std_utils.cmx
File "std_utils.ml", line 344, characters 30-48:
344 |     let rec assoc_lbl ?(cmp = Pervasives.compare) ~default x = function
                                    ^^^^^^^^^^^^^^^^^^
Error: Unbound module Pervasives
make[2]: *** [Makefile:1347: std_utils.cmo] Error 2
```

**Comment by rwmjones** [comment]
We've not built virt-v2v on OCaml 5 yet, but the above error should be easy to fix, simply replace every instance of `Pervasives.` with `Stdlib.` in the source code.

**Comment by solsticedhiver** [comment]
This seems to do it, but I bumped into another archlinux issue about
```
Error: /usr/lib/ocaml/guestfs/guestfs.cmi
       is not a compiled interface for this version of OCaml.```

**Comment by rwmjones** [comment]
That'll be because the libguestfs package was built with OCaml != 5.

**Comment by juergenhoetzel** [comment]
> That'll be because the libguestfs package was built with OCaml != 5.

This was indeed not a upstream issue. Fixed in Arch Linux [extra] repo:

https://gitlab.archlinux.org/archlinux/packaging/packages/libguestfs/-/commit/4780699838e5fad70eb8e031438392dced998868

**Comment by solsticedhiver** [comment]
I don't understand why you are saying that. Because your fix includes a patch called ocaml5.patch to help build against ocaml 5.....
